#  MLPACK 1.0.6:
#  A Scalable C++  Machine Learning Library
library: mlpack
methods:
    PCA:
        script: methods/mlpack/pca.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/cities.csv', 'datasets/faces.csv', 'datasets/iris.csv', 'datasets/wine.csv', 'datasets/artificial_data.csv']

            - files: ['datasets/cities.csv', 'datasets/iris.csv', 'datasets/wine.csv', 'datasets/artificial_data.csv']
              options: '-d 2'

            - files: ['datasets/cities.csv', 'datasets/faces.csv', 'datasets/iris.csv', 'datasets/wine.csv', 'datasets/artificial_data.csv']
              options: '-d 2 -s'
    NMF:
        script: methods/mlpack/nmf.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/piano_magnitude_spectogram.csv']
              options: '-r 6 -s 42 -u multdist'

            - files: ['datasets/piano_magnitude_spectogram.csv']
              options: '-r 6 -s 42 -u multdiv'

            - files: ['datasets/piano_magnitude_spectogram.csv', 'datasets/pendigits.csv']
              options: '-r 6 -s 42 -u als'
    KMeans:
        script: methods/mlpack/kmeans.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/waveform.csv']
              options: '-c 2'

            - files: ['datasets/wine.csv', 'datasets/iris.csv']
              options: '-c 3'

            - files: ['datasets/cloud.csv']
              options: '-c 5'

            - files: ['datasets/USCensus1990.csv']
              options: '-c 6'

            - files: ['datasets/covtype.csv', 'datasets/wine_qual.csv']
              options: '-c 7'

            - files: ['datasets/USCensus1990.csv']
              options: '-c 8'

            - files: ['datasets/USCensus1990.csv']
              options: '-c 12'

            - files: ['datasets/isolet.csv']
              options: '-c 26'
    NBC:
        script: methods/mlpack/nbc.py
        format: [csv, txt]
        datasets:
            - files: [ ['datasets/iris_train.csv', 'datasets/iris_test.csv'] ]
    KPCA:
        script: methods/mlpack/kernel_pca.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/circle_data.csv']
              options: '-k linear'

            - files: ['datasets/circle_data.csv', 'datasets/abalone.csv' , 'datasets/cal_housing.csv', 'datasets/bank8FM.csv', 'datasets/stock.csv']
              options: '-k gaussian'

            - files: ['datasets/circle_data.csv', 'datasets/abalone.csv' , 'datasets/cal_housing.csv', 'datasets/bank8FM.csv', 'datasets/stock.csv']
              options: '-k polynomial'

            - files: ['datasets/circle_data.csv', 'datasets/abalone.csv' , 'datasets/cal_housing.csv', 'datasets/bank8FM.csv', 'datasets/stock.csv']
              options: '-k hyptan'

            - files: ['datasets/circle_data.csv', 'datasets/abalone.csv' , 'datasets/cal_housing.csv', 'datasets/bank8FM.csv', 'datasets/stock.csv']
              options: '-k laplacian'

            - files: ['datasets/circle_data.csv', 'datasets/abalone.csv' , 'datasets/cal_housing.csv', 'datasets/bank8FM.csv', 'datasets/stock.csv']
              options: '-k cosine'
    LARS:
        script: methods/mlpack/lars.py
        format: [csv, txt]
        datasets:
            - files: [ ['datasets/diabetes_X.csv', 'datasets/diabetes_y.csv'], ['datasets/cosExp_X.csv', 'datasets/cosExp_y.csv'], ['datasets/arcene_X.csv', 'datasets/arcene_y.csv'], ['datasets/madelon_X.csv', 'datasets/madelon_y.csv'] ]
              options: '--lambda1 0.01 --lambda2 0.005'

            - files: [ ['datasets/diabetes_X.csv', 'datasets/diabetes_y.csv'], ['datasets/cosExp_X.csv', 'datasets/cosExp_y.csv'], ['datasets/arcene_X.csv', 'datasets/arcene_y.csv'], ['datasets/madelon_X.csv', 'datasets/madelon_y.csv'] ]
              options: '--lambda1 0.01 --lambda2 0.005 --use_cholesky'
    LSH:
        script: methods/mlpack/lsh.py
        format: [csv, txt]
        datasets:
         - files: ['datasets/wine.csv', 'datasets/cloud.csv', 'datasets/isolet.csv', 'dataset/covtype.csv', 'datasets/wine_qual.csv']
           options: '-k 3 -s 42'
    ALLKNN:
        script: methods/mlpack/allknn.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s 42'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s 42 -S'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s 42 -c'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s 42 -c -S'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s 42 -N'
    ALLKFN:
        script: methods/mlpack/allkfn.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -s'

            - files: ['datasets/wine.csv', 'datasets/cloud.csv']
              options: '-k 3 -N'
    RANGESEARCH:
        script: methods/mlpack/range_search.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/wine.csv', 'datasets/artificial_40D.csv']
              options: '--min=1.3 --max=20.3'

            - files: ['datasets/wine.csv', 'datasets/artificial_40D.csv']
              options: '--min=1.3 --max=20.3 -N'

            - files: ['datasets/wine.csv', 'datasets/artificial_40D.csv']
              options: '--min=1.3 --max=20.3 -s'
    GMM:
        script: methods/mlpack/gmm.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/artificial_2DSignal.csv', 'datasets/artificial_5DSignal.csv', 'datasets/iris.csv', 'datasets/vehicle.csv', 'datasets/wine.csv', 'datasets/USCensus1990.csv', 'datasets/optdigits.csv', 'datasets/isolet.csv']
              options: '-s 42'

            - files: ['datasets/artificial_2DSignal.csv', 'datasets/iris.csv', 'datasets/vehicle.csv', 'datasets/wine.csv', 'datasets/USCensus1990.csv', 'datasets/isolet.csv']
              options: '-P -s 42'
    DET:
        script: methods/mlpack/det.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/iris.csv', 'datasets/cloud.csv']

            - files: ['datasets/iris.csv', 'datasets/cloud.csv', ['datasets/diabetes_X.csv', 'datasets/diabetes_y.csv'] ]
              options: '-f 0'

            - files: [ ['datasets/diabetes_X.csv', 'datasets/diabetes_y.csv'], ['datasets/madelon_X.csv', 'datasets/madelon_y.csv'] ]
    EMST:
        script: methods/mlpack/emst.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/iris.csv', 'datasets/vehicle.csv', 'datasets/waveform.csv']

            - files: ['datasets/iris.csv']
              options: '-n'
