#  MLPACK 1.0.6:
#  A Scalable C++  Machine Learning Library
library: mlpack
methods:
    PCA:
        script: methods/mlpack/pca.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/cities.csv', 'datasets/faces.csv']

            - files: ['datasets/cities.csv']
              options: '-d 2'
    NMF:
        script: methods/mlpack/nmf.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/piano_magnitude_spectogram.csv']
              options: '-r 6 -s 42 -u multdist'

            - files: ['datasets/piano_magnitude_spectogram.csv']
              options: '-r 6 -s 42 -u multdiv'

            - files: ['datasets/piano_magnitude_spectogram.csv']
              options: '-r 6 -s 42 -u als'
